version: '2.2'
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    container_name: TS-postgreSQL-Database
    environment:
      POSTGRES_DB: TS
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: TS-pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: b10923057@gemail.yuntech.edu.tw
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9101:80"
    links:
      - "db:pgsql-server"